### ISSUE TITLE
search also gets encrypted

### ISSUE THREAD

**Issue by abhimanyuchawla** [CoinK0in/mkdocs-encryptcontent-plugin#13] opened 2021-06-10 16:34 UTC
I am encrypting all pages using a global password, and it turns out the search index file (site/search/search_index.json) also gets encrypted.
When viewing the site in a browser, I am able to decrypt each page using the global password, but the search is still encrypted.

One would expect the search to also get decrypted after supplying the global password.
Is there a way you could fix this, or add some option which prevents the search_index.json file to get encrypted in the first place.

Thank you.

**Comment by CoinK0in** [comment] 2021-06-12 21:22
I confirm that on the current version (1.0.0) the search does not work on encrypted pages. 
I added an option [do-not-encrypt-search-index](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#do-not-encrypt-search-index) to choose if the 'text' search index should be encrypted or not, in version 1.1.0.

I continue to check if it would be possible to, fully or partially, decrypt the search index 'on the fly' when entering a password.
But it seems complicated to generalize since the search engines are included in theme's and therefore specific. And this process should be entirely done in JS, which is definitely not my thing ... :dizzy_face:

**Comment by abhimanyuchawla** [comment] 2021-06-14 17:21
Hi,
Thanks for your prompt fix, much appreciated. I confirm that version 1.1.0 allows one to exclude the search index from encryption.
It would be nice to have the search decrypted 'on the fly', but I understand it would be tough to do that for all search engines.
But this fix works for my use case, thanks once again!

**Comment by CoinK0in** [comment] 2021-06-14 19:30
Your welcome.

I keep trying to make a version of the search engine that could decrypt the search index 'on the fly' and be integrated easly to any template. I probably make a new version if I get a result that's satisfy me.

I close this issue. Fell free to open a new issue if you have any troubles :)

**Closed by CoinK0in** 2021-06-14 19:30 UTC
Labels: enhancement

**Comment by CoinK0in** [comment] 2021-08-25 10:52
I pushed some time ago an experimental branch [Search index encryption](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/tree/experimental#search-index-encryptionv). I added different way of managing the search index with this encryption plugin. One mode,  "dynamic", seems to meet your expectations.

Could you try it ? Do you have an opinion on it ? Your feedback are welcome :)

**Comment by abhimanyuchawla** [comment] 2021-09-09 18:39
Hi
Sorry for the delay, I was on vacation.
Thanks for adding this feature. I tried the experimental branch, however I see this warning when I start mkdocs server:
WARNING  -  Config value: 'plugins'. Warning: ('decrypt_search', 'Unrecognised configuration name: decrypt_search')
I checked that I am infact using the experimental branch (Version: 1.2.0.1), and not the master branch.
Is it possible that since I am using Material theme that the feature is not working?
Thanks.

**Comment by CoinK0in** [comment] 2021-09-10 07:51
I confirm this feature does not work with the Material theme :/
The Material theme modifies the way searches work after generating the site by adding its own javascript files. 
I haven't been able to find a "clean" way to transform these files from this plugin.

I will try to make the necessary modifications in the Javascript files used by the Material theme to reproduce the behaviour with the default theme from mkdocs. I could not automatically manage the modifications / installation of these modified files, so it will probably be necessary to manually modify the javascript files in the Material themes (With all the implications that this will have on version upgrades, bug fixes , etc.). 

Thank you for taking it to try this feature and for providing feedback on its use.

**Comment by abhimanyuchawla** [comment] 2021-09-14 19:59
Thank you for your efforts. Much appreciated.
