### ISSUE TITLE
How to render math formula on the protected page

### ISSUE THREAD

**Issue by luzai** [CoinK0in/mkdocs-encryptcontent-plugin#12] opened 2020-11-19 12:46 UTC
Hi, thank you very much for this plugin! 

I would like to use it to protect some technical reports with math formulas, however, after entering the password, the formula cannot be rendered and is shown as raw text. Without password protection, the formula can be rendered. May I ask how to render math formula on the protected page?

**Comment by CoinK0in** [comment] 2020-11-19 23:43
Thanks for your feedback.

This plugin encrypts the content of a page after the Markdown text is rendered to HTML.
The HTML before and after decryption must be the same, so maybe you use some JavaScript to render your formula ?
If this assumption is correct, there is no way in the current version, but i thing i can try to do something in [decrypt-form.tpl.html](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/blob/c4c870524dcddbab3d29c75c978c6d144258a434/encryptcontent/decrypt-form.tpl.html#L140)

Could you give me other information on how the rendering of formulas works on your site ?
Maybe some examples that I can reproduce on my side to work on it.
Thanks.

**Comment by luzai** [comment] 2020-11-20 00:53
Thank you very much for your reply! 

I prepare a simple example here https://luzai.github.io/test-encrypted/, the password is 123456. The corresponding repo is https://github.com/luzai/test-encrypted. 

Thank you.

**Comment by CoinK0in** [comment] 2020-11-20 13:45
I added a detection of the Arithmatex module which, if present, should relaunch the rendering of the math equations.
No additional configuration is needed for  [Arithmatex support](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#arithmatex-support).

[Version 0.0.13](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/releases/tag/0.0.13) improve math equation rendering.
All comments, improvements, corrections are welcome because I only validate the operation on the `generic` part of Arithmatex.

**Comment by luzai** [comment] 2020-11-20 23:51
Thank you very much! I tested the new version with Arithmatex support, it renders the math equation successfully!

**Comment by CoinK0in** [comment] 2020-11-20 23:57
I close this issue but feel free to reopen it if you have any trouble with this extension :)

**Closed by CoinK0in** 2020-11-20 23:57 UTC

**Comment by TQuantX** [comment] 2021-07-17 17:55
Hi, 
sorry to bother you. I have tried to use it too, which seems to work. However, no updates, the lateX formulas stay in their lateX form, and the python file using pyodide do not appear, after the password is entered. 
For instance 
- https://tquantx.gitlab.io/nsi_en_ligne/maths.html > pwd : maths  for the maths formula
- https://tquantx.gitlab.io/nsi_en_ligne/nsi_terms/chpKNN/KNN.html > pwd : KNN where python code should appear in the last box
my configurations files are 
- https://gitlab.com/TQuantX/nsi_en_ligne/-/blob/master/mkdocs.yml 
- https://gitlab.com/TQuantX/nsi_en_ligne/-/blob/master/.gitlab-ci.yml

Could you help me ? I tried to do as you say in the readme.md file

**Comment by CoinK0in** [comment] 2021-07-18 15:26
No problem, ur welcome.
I need to know the versions of the packages you are using.
Mainly those related to mkdocs `pip3 list | grep mkdocs` to verify that it doesn't have a version incompatibility.

When I clone your repo I reproduce the problem of formatting lateX formulas. However when I don't use your "overrides" configuration files and I put those of the theme material back by default, I no longer have the problem of rendering on the mathematical functions. I think something is wrong with your current "override" setup.  

For the 'pyodide' part, I will be looking at the beginning of the week how it works and what is needed / lacking on my plugin to make it work.
